window.PORTFOLIO_CONTENT = {
  hero: {
    kicker: "AI Vibe Coding / Photography Portfolio",
    title: "Focus the frame. Enter the work.",
    description:
      "我用 AI 做实验，用文字整理判断，用摄影保存观看。这个 portfolio 从一次对焦开始。",
  },
  heroPhotos: [
    { src: "assets/photos/inbox/pacific-sunset.jpg", alt: "海边日落与潮线" },
    { src: "assets/photos/inbox/snow-peak-mono.jpg", alt: "黑白雪山与强光" },
    { src: "assets/photos/inbox/westminster-dusk.jpg", alt: "黄昏下的伦敦天际线" },
    { src: "assets/photos/inbox/rain-window.jpg", alt: "雨天车窗后的城市" },
    { src: "assets/photos/inbox/platform-light.jpg", alt: "阳光下的空站台" },
    { src: "assets/photos/inbox/quiet-cyclist.jpg", alt: "街口骑车的人" },
    { src: "assets/photos/inbox/red-geraniums-inbox.jpg", alt: "暗处的红色花朵" },
  ],
  workPanels: [
    {
      number: "01",
      title: "AI Vibe Coding",
      description: "把模糊想法变成小工具、界面原型和可复盘的创作流程。",
      href: "projects.html",
    },
    {
      number: "02",
      title: "Process & Interaction",
      description: "把摄影里的取景、对焦、曝光、显影，转译成网页进入和滚动体验。",
      href: "projects.html",
    },
    {
      number: "03",
      title: "Photography",
      description: "用系列作品、街头观察和商业拍摄整理我的观看方式。",
      href: "photography.html",
      image: "assets/photos/tree-canopy.jpg",
      alt: "树冠之间的天空",
    },
  ],
  projects: [
    {
      meta: "AI Work / Local-first Sourcing Platform / 2026",
      title: "Recruiting Any",
      description: "一个从 Discover 到 Pool 再到 Outreach 的 AI sourcing 实验，把研究、搜索、候选人资料和个性化触达放进同一个本地工作流。",
      href: "https://github.com/alexlxy599/recruiting-any",
    },
    {
      meta: "Interface / Personal System / 2026",
      title: "Personal OS Dashboard",
      description: "把日程、灵感、任务和写作片段聚合成一个低噪音的个人界面。",
      href: "#",
    },
    {
      meta: "Research / Photography Critique / 2025",
      title: "AI Photography Critic",
      description: "尝试让模型从构图、色彩、叙事和观看路径上给照片做结构化反馈。",
      href: "#",
    },
  ],
  photoBreak: {
    src: "assets/photos/inbox/pacific-sunset.jpg",
    alt: "海边日落与潮线",
    text: "A practice of attention, patience, and finishing things with care.",
  },
  photos: [
    {
      src: "assets/photos/inbox/subway-platform.jpg",
      title: "Platform",
      alt: "地铁站台上的人影",
      layout: "wide",
    },
    {
      src: "assets/photos/inbox/pacific-sunset.jpg",
      title: "Pacific Sunset",
      alt: "海边日落与潮线",
      layout: "large",
    },
    {
      src: "assets/photos/inbox/snow-peak-mono.jpg",
      title: "Snow Peak",
      alt: "黑白雪山与强光",
      layout: "",
    },
    {
      src: "assets/photos/inbox/subway-crowd.jpg",
      title: "Crowd Study",
      alt: "地铁站里的俯视人群",
      layout: "tall",
    },
    {
      src: "assets/photos/inbox/gulls-at-sunset.jpg",
      title: "Gulls",
      alt: "日落时飞过的人群与海鸟",
      layout: "",
    },
    {
      src: "assets/photos/inbox/sunset-frame.jpg",
      title: "Through Glass",
      alt: "窗框里的海上日落",
      layout: "wide",
    },
    {
      src: "assets/photos/inbox/roof-gull.jpg",
      title: "Roof Gull",
      alt: "屋檐上的海鸥",
      layout: "tall",
    },
    {
      src: "assets/photos/inbox/red-light-figure.jpg",
      title: "Red Light",
      alt: "红色光线照亮的人物",
      layout: "wide",
    },
    {
      src: "assets/photos/inbox/winter-mountain.jpg",
      title: "Winter Mountain",
      alt: "雪地中的山脉",
      layout: "",
    },
    {
      src: "assets/photos/inbox/street-elder.jpg",
      title: "Street Elder",
      alt: "阳光街道上的老人",
      layout: "",
    },
    {
      src: "assets/photos/inbox/wheel-field.jpg",
      title: "Wheel Field",
      alt: "草地远处的摩天轮",
      layout: "tall",
    },
    {
      src: "assets/photos/inbox/market-stroller.jpg",
      title: "Market Shade",
      alt: "市场棚下的人和婴儿车",
      layout: "wide",
    },
    {
      src: "assets/photos/inbox/church-tower.jpg",
      title: "Church Tower",
      alt: "蓝天下的教堂塔楼",
      layout: "tall",
    },
    {
      src: "assets/photos/inbox/evening-couple.jpg",
      title: "Evening Pair",
      alt: "黄昏里靠在一起的人",
      layout: "tall",
    },
    {
      src: "assets/photos/inbox/fireworks-bridge.jpg",
      title: "Fireworks",
      alt: "桥边夜空中的烟花",
      layout: "wide",
    },
    {
      src: "assets/photos/inbox/sailboat-swimmer.jpg",
      title: "Sailboat",
      alt: "海面上的帆船与游泳者",
      layout: "wide",
    },
    {
      src: "assets/photos/inbox/birds-between-buildings.jpg",
      title: "Birds Between Buildings",
      alt: "楼宇间飞过的鸟",
      layout: "",
    },
    {
      src: "assets/photos/inbox/lake-silhouette.jpg",
      title: "Lake Silhouette",
      alt: "湖边的人影和山",
      layout: "tall",
    },
    {
      src: "assets/photos/inbox/wind-window.jpg",
      title: "Wind Window",
      alt: "车窗外的风车与暮色",
      layout: "wide",
    },
    {
      src: "assets/photos/inbox/vending-machines.jpg",
      title: "Vending Machines",
      alt: "街边自动售货机",
      layout: "",
    },
  ],
  about: {
    kicker: "About",
    title: "一个在 AI、文字和摄影之间来回试东西的人。",
    description:
      "我关心工具如何改变创作，也关心人如何在更快的技术节奏里保留自己的观看、判断和手感。这个网站会持续更新我的项目、文章和摄影系列。",
  },
  links: [
    { label: "Email", href: "mailto:hello@example.com" },
    { label: "GitHub", href: "#" },
    { label: "Instagram", href: "#" },
  ],
};
